# Generated by Django 5.1.1 on 2025-12-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='channels',
            field=models.ManyToManyField(blank=True, to='monitoring.channel'),
        ),
    ]
