# Generated by Django 5.1.1 on 2025-12-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('webhook', 'Webhook')], max_length=20)),
                ('target', models.CharField(help_text='Email, chat ID, phone ID ou URL webhook', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='alertrule',
            name='channels',
        ),
        migrations.AddField(
            model_name='alertrule',
            name='channels',
            field=models.ManyToManyField(blank=True, to='monitoring.channel'),
        ),
    ]
